c_stdlib_version:           # [osx and x86_64]
  - 10.14                   # [osx and x86_64]

c_stdlib_version:   # [linux]
  - "2.17"          # [linux]

channel_sources:
  - conda-forge/label/py_build_cmake_dev,conda-forge
