{% set name = "openvino-tokenizers" %}
{% set version = "2025.2.0" %}

# Libraries on Windows are expected to be installed into LIBRARY_PREFIX.
# See https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html.
# On non-Windows CMAKE_ARGS already contains CMAKE_INSTALL_PREFIX.
{% if win %}
    {% set cmake_args = "%CMAKE_ARGS% -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX%" %}
{% else %}
    {% set cmake_args = "$CMAKE_ARGS -DCMAKE_SKIP_INSTALL_RPATH=ON" %}
    {% if target_platform != build_platform %}
        {% set cmake_args = cmake_args + " -DProtobuf_PROTOC_EXECUTABLE=$BUILD_PREFIX/bin/protoc" %}
    {% endif %}
    {% if target_platform == "osx-64" %}
        {% set cmake_args = cmake_args + " -DCMAKE_CXX_FLAGS=-D_LIBCPP_DISABLE_AVAILABILITY" %}
    {% endif %}
{% endif %}
{% set cmake_args = cmake_args + " -DOPENVINO_TOKENIZERS_INSTALL_BINDIR=bin -DOPENVINO_TOKENIZERS_INSTALL_LIBDIR=lib" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/openvinotoolkit/openvino_tokenizers/archive/refs/tags/{{ version }}.0.tar.gz
  sha256: 0c37cbd15e961a274d1dc841859df10f235e0a257acd68c4f3ca3072b2a7c1c9
  patches:
    - patches/0001-fix-libsentencepiece-integration.patch
    - patches/0002-fix-python-version-bounds.patch

build:
  number: 0

outputs:
  - name: libopenvino-tokenizers
    version: {{ version }}
    about:
      summary: OpenVINO Tokenizers C++ library
      license_file:
        - LICENSE
        - third-party-programs.txt
    build:
      script:
        - cmake {{ cmake_args }} -DENABLE_SYSTEM_ICU=ON -S . -B build
        - cmake --build build --parallel --config Release --verbose
        - cmake --install build --config Release
      ignore_run_exports_from:
        - libopenvino-dev
      run_exports:
        - {{ pin_subpackage('libopenvino-tokenizers', max_pin='x.x.x') }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - make  # [unix]
        - cmake
        - libprotobuf
      host:
        - bzip2
        - icu
        - libopenvino-dev ={{ version }}
        - libprotobuf
        - libsentencepiece
        - libabseil
        - tbb-devel
        - zlib
      run:
        - {{ pin_compatible('libopenvino', max_pin='x.x.x') }}
    test:
      requires:
        - {{ compiler('cxx') }}
        - cmake
        - libopenvino-dev ={{ version }}
        - ninja
      files:
        - samples/
      commands:
        - test -f $PREFIX/lib/libopenvino_tokenizers${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_BIN%\\openvino_tokenizers%SHLIB_EXT% exit 1  # [win]

        - cmake -S samples -B build -DCMAKE_CXX_FLAGS=-D_LIBCPP_DISABLE_AVAILABILITY -DCMAKE_BUILD_TYPE=Release -G Ninja
        - cmake --build build --parallel
        - ./build/hello_tokenizers  # [unix]
        - .\\build\\hello_tokenizers  # [win]

  - name: openvino-tokenizers
    version: {{ version }}
    script: install_python.sh
    about:
      summary: OpenVINO Tokenizers
      license_file:
        - LICENSE
        - third-party-programs.txt
    build:
      string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
      entry_points:
        - convert_tokenizer = openvino_tokenizers.cli:convert_hf_tokenizer
    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - make  # [unix]
        - cmake
      host:
        - pip
        - python
        - setuptools
        - py-build-cmake
        - libopenvino-python ={{ version }} # dummy dependency, because pyproject.toml contains 'openvino' dependency
      run:
        - {{ pin_subpackage('libopenvino-tokenizers', exact=True) }}
        - {{ pin_compatible('libopenvino-python', max_pin='x.x.x') }}
    test:
      imports:
        - openvino_tokenizers
      requires:
        - pip
      commands:
        - pip check

about:
  home: https://github.com/openvinotoolkit/openvino_tokenizers
  summary: 'OpenVINO Tokenizers'
  description: |
    OpenVINO tokenizers module allows to convert tokenizers from Hugging Face library and execute
    them as OpenVINO IRs.
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - third-party-programs.txt
  doc_url: https://github.com/openvinotoolkit/openvino_tokenizers
  dev_url: https://github.com/openvinotoolkit/openvino_tokenizers

extra:
  feedstock-name: openvino-tokenizers
  recipe-maintainers:
    - ilya-lavrenov
    - mryzhov
    - apaniukov
    - h-vetinari
