{% set name = "openvino-tokenizers" %}
{% set version = "2024.1.0" %}

{% set install_args = "-vv --config-settings=wheel.cmake=False" %}

# Libraries on Windows are expected to be installed into LIBRARY_PREFIX.
# See https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html.
# On non-Windows CMAKE_ARGS already contains CMAKE_INSTALL_PREFIX.
{% if win %}
    {% set cmake_args = "%CMAKE_ARGS% -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX%" %}
{% else %}
    {% set cmake_args = "$CMAKE_ARGS" %}
{% endif %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/openvinotoolkit/openvino_tokenizers/archive/refs/tags/2024.1.0.0.tar.gz
  sha256: c14cdd7b3be8365c8e637161afc32b96f598b21d6cece4d134df39e3ebc6505c

build:
  number: 0

outputs:
  - name: libopenvino-tokenizers
    version: {{ version }}
    about:
      summary: OpenVINO Tokenizers C++ library
      license_file:
        - LICENSE
        - third-party-programs.txt
    build:
      script:
        - cmake {{ cmake_args }} -DCMAKE_SKIP_INSTALL_RPATH=ON -DCMAKE_BUILD_TYPE=Release -S . -B build
        - cmake --build build --parallel --config Release
        - cmake --install build --config Release
      ignore_run_exports_from:
        - libopenvino-dev
      run_exports:
        - {{ pin_subpackage('libopenvino-tokenizers', max_pin='x.x.x') }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - sysroot_linux-64 =2.17  # [linux64]
        - make  # [not win]
        - cmake >=3.15
      host:
        - libopenvino-dev ={{ version }}
      run:
        - {{ pin_compatible('libopenvino', max_pin='x.x.x') }}
    test:
      requires:
        - {{ compiler('cxx') }}
        - cmake >=3.15
        - libopenvino-dev ={{ version }}
        - ninja
      files:
        - samples/
      commands:
        - test -f $PREFIX/lib/libopenvino_tokenizers${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_BIN%\\openvino_tokenizers%SHLIB_EXT% exit 1  # [win]

        - cmake -S samples -B build -DCMAKE_BUILD_TYPE=Release -G Ninja
        - cmake --build build --parallel
        - ./build/hello_tokenizers  # [unix]
        - .\\build\\hello_tokenizers  # [win]

  - name: openvino-tokenizers
    version: {{ version }}
    about:
      summary: OpenVINO Tokenizers
      license_file:
        - LICENSE
        - third-party-programs.txt
    build:
      script: "$PYTHON -m pip install . {{ install_args }}"  # [unix]
      script: "%PYTHON% -m pip install . {{ install_args }}"  # [win]
      string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
      entry_points:
        - convert_tokenizer = openvino_tokenizers.cli:convert_hf_tokenizer
    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
      host:
        - pip
        - python
        - scikit-build-core
        - libopenvino-python ={{ version }} # dummy dependency, because pyproject.toml contains 'openvino' dependency
      run:
        - {{ pin_subpackage('libopenvino-tokenizers', exact=True) }}
        - {{ pin_compatible('libopenvino-python', max_pin='x.x.x') }}
    test:
      imports:
        - openvino_tokenizers
      requires:
        - pip
      commands:
        - pip check

about:
  home: https://github.com/openvinotoolkit/openvino_tokenizers
  summary: 'OpenVINO Tokenizers'
  description: |
    OpenVINO tokenizers module allows to convert tokenizers from Hugging Face library and execute
    them as OpenVINO IRs.
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - third-party-programs.txt
  doc_url: https://github.com/openvinotoolkit/openvino_tokenizers
  dev_url: https://github.com/openvinotoolkit/openvino_tokenizers

extra:
  feedstock-name: openvino-tokenizers
  recipe-maintainers:
    - ilya-lavrenov
    - mryzhov
    - apaniukov
