azure:
  settings_win:
    pool:
      vmImage: windows-2019
  store_build_artifacts: true
build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
channel_priority: strict
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
os_version:
  linux_64: cos7
test: native_and_emulated
noarch_platforms:
  - linux_64
provider:
  linux_aarch64: azure